appium/appium-chromedriver

- test/chromedriver-specs.js
- jshint failing due to unused import
> Removing unused import

- README.md
- lib/install.js
It will very helpful for users from China.
> Support custom chromedriver CDN url

- lib/chromedriver.js
- package.json
> Update JSONWP proxy

- package.json
> Fix install issues

- README.md
- install-npm.js
- package.json
Finally figured out a way to get it working reliably.
> Settle on an install system

- lib/chromedriver.js
- test/install-specs.js
Chromedriver side of #35. Still need to figure out how to expose these to the client through Appium.
> Allow use of verbose and log-dir flags

- lib/chromedriver.js
There is a chance that we've thrown an error before `proc` is initialized.
See https://github.com/appium/appium/issues/6510
> Add check if proc exists

- lib/chromedriver.js
- lib/install.js
- package.json
- test/chromedriver-specs.js
- test/install-specs.js
> Update to CD 2.24

- .travis.yml
> Test on more node versions

- lib/install.js
> Update ChromeDriver to 2.26

- lib/install.js
> Update to latest chromedriver

- lib/install.js
- package.json
- test/chromedriver-specs.js
* Ran tests without adm-zip and verified that they fail because of it
* Replaced adm-zip with appium-support zip
* The tests pass again
* Also fixed an uncaught promise error in chromedriver-specs.js
(reviewers @imurchie @jlipps)
> Removed adm-zip dependency

- .gitignore
- lib/chromedriver.js
Addresses https://github.com/appium/appium/issues/8566#issuecomment-304853144
> Add link to version docs when erroring

- lib/chromedriver.js
- package.json
- test/chromedriver-specs.js
> Fix the build

- lib/chromedriver.js
In the documentation rewrite the address was changed.
> Fix link to CD docs

- lib/install.js
- package.json
See https://github.com/appium/appium/issues/9866
> Update lodash from 3 to 4

- package.json
- test/chromedriver-specs.js
- test/install-specs.js
Add a gulp task for fixing eslint. And fix the arrow functions in mocha.
appium/appium#10016
> Get rid of arrow functions in mocha apparatus

- LICENSE
- lib/install.js
https://chromedriver.storage.googleapis.com/2.36/notes.txt
> Update to CD 2.36

- lib/chromedriver.js
`_statePromise()` seems not used. So I removed it.
> Remove unused method _statePromise()

- lib/chromedriver.js
This might be handy to properly set up the content of chromedrivers folder.
> Improve errors description for better chromedriver lookup issues handling

- lib/chromedriver.js
Addresses https://github.com/appium/appium/issues/11431
> Make version number parsing more flexible

- .travis.yml
Simply remove unnecessary line in config
> Update sudo in travis

- lib/chromedriver.js
Chromedriver 2.45 [has been released](https://chromedriver.storage.googleapis.com/index.html?path=2.45/):
```
----------ChromeDriver v2.45 (2018-12-10)----------
Supports Chrome v70-72
Resolved issue 1997: New Session is not spec compliant [[Pri-1]]
Resolved issue 2685: Should Assert that the chrome version is compatible [[Pri-2]]
Resolved issue 2677: Find Element command returns wrong error code when an invalid locator is used [[Pri-2]]
Resolved issue 2676: Some ChromeDriver status codes are wrong [[Pri-2]]
Resolved issue 2665: compile error in JS inside of WebViewImpl::DispatchTouchEventsForMouseEvents [[Pri-2]]
Resolved issue 2658: Window size commands should handle user prompts [[Pri-2]]
Resolved issue 2684: ChromeDriver doesn't start Chrome correctly with …
```
> Upgrade to CD 2.45

- lib/chromedriver.js
- test/chromedriver-e2e-specs.js
Fixes https://github.com/appium/appium/issues/12223
> Make sure ALL the browser console logs get in

- .travis.yml
- install-npm.js
- package.json
Build on windows. Also move lifecycle scripts around to ensure that the code is transpiled before we try to use it.
> Add windows to Travis build

- lib/chromedriver.js
- lib/protocol-helpers.js
- package.json
- test/chromedriver-e2e-specs.js
- test/protocol-helpers-specs.js
Chromedriver since v75 is fully compatible to w3c standard. This means it expects all caps to be properly prefixed and the session capabilities to be passed in the appropriate format. Although, everything stays the same for older CD versions.
> feat: Add support for W3C session capabilities format

- lib/chromedriver.js
http://chromedriver.chromium.org/downloads
77 is still in beta
> feat: add Chromedriver 76.0.3809.126

- lib/storage-client.js
- test/storage-client-e2e-specs.js
https://github.com/appium/appium/issues/13781
> fix: Improve the drivers lookup logic for older Chrome versions

- lib/chromedriver.js
- package.json
Addresses https://github.com/appium/appium/issues/13912
> fix: Properly format chromedriver versions mapping before storing them into a file

- lib/chromedriver.js
Addresses https://github.com/appium/appium/issues/14161
> fix: Coerce chromedriver version before comparing it

- lib/chromedriver.js
- package.json
https://github.com/appium/appium/issues/14169
> fix: Avoid repeated storage sync if the driver is already downloaded

- lib/chromedriver.js
The second part of https://github.com/appium/appium-android-driver/pull/626 implementation
> feat: Retrieve browser version from details property if it is supplied

- package.json
https://travis-ci.org/github/appium/appium/jobs/679878626
> fix: add config into package

- lib/chromedriver.js
- package.json
https://github.com/appium/appium/issues/14434
> chore: Do not retry driver session startup

- lib/chromedriver.js
issue: https://github.com/appium/appium/issues/14583
> fix: kill forwarded by device

- .github/workflows/node.js.yml
- package.json
https://github.com/appium/appium-chromedriver/runs/1881737737
> fix: Try to use the most recent chromedriver version in e2e tests if no direct match has been found

- lib/chromedriver.js
Related to https://github.com/appium/appium/issues/16730
> fix: Make sure all chromedriver teardown steps are always executed

- lib/chromedriver.js
- test/chromedriver-specs.js
Addresses https://github.com/appium/appium/issues/16863
> fix: Tune glob usage on Windows

- install-npm.js
Addresses https://github.com/appium/appium/issues/17278
> fix: Update require for fs/promise module

- lib/chromedriver.js
- lib/install.js
- lib/protocol-helpers.js
- lib/storage-client.js
- lib/utils.js
- package.json
- test/functional/install-e2e-specs.js
- test/functional/storage-client-e2e-specs.js
- test/unit/chromedriver-specs.js
Related to https://github.com/appium/appium/issues/17806
> chore: Remove peer dependency to Appium

- lib/storage-client.js
- lib/utils.js
Addresses https://github.com/appium/appium/issues/18136
> fix: Update Apple ARM architecture detection

- lib/index.ts
> fix(types): actually export named Chromedriver

- .github/workflows/unit-test.yml
- lib/chromedriver.js
- package.json
This should also reduce CPU load
> chore: Optimize process events handling

- lib/storage-client/googleapis.js
- tsconfig.json
Same as https://github.com/appium/appium-chromedriver/pull/424, just with fixes and backward compatibility included
> fix: Support xmldom 0.9.0+

- lib/storage-client/googleapis.js
- package.json
The same as https://github.com/appium/appium/pull/20537
> fix: build error with type of xmldom

- lib/chromedriver.js
- lib/storage-client/googleapis.js
- lib/storage-client/storage-client.js
- lib/types.ts
- test/unit/utils-specs.js
> refactor: fix typos

- package.json
instead of https://github.com/appium/appium-chromedriver/pull/413
> chore: remove no reference dev deps rimraf
