lib/install.js

From official changelog: https://chromedriver.storage.googleapis.com/2.16/notes.txt
```
----------ChromeDriver v2.16 (2015-06-08)----------
Supports Chrome v42-45
```
And a bit more from commit history: https://github.com/bayandin/chromedriver/compare/2.15...2.16

Update chromedriver to 2.16

---

install-npm.js
lib/install.js

People sometimes try to run `./install-npm.js`.

Add hashbang to install script so it can be run on its own

---

index.js
install-npm.js
lib/install.js

When installing from a parent module, the install script tries to run before all the required dependencies are installed. This most often manifests as not being able to find `babel-runtime` files. To alleviate this, try to import the real install file, and keep doing it until it works.

Add retry logic to install script

---

install-npm.js
package.json

If the transpile process hadn't happened, we would get into a long loop trying to install the binary, which could never happen.

Do install script after prepublish

---

lib/chromedriver.js

Fixes a bug which causes killing of all user's processes in Ubuntu 16.04 if no previous chromedriver instances are present. This behaviour is described [here][1] and [here][2].
Tests were run and pass under Ubuntu 16.04 and OS X El Capitan 10.11.4.
[1]: http://ubuntuforums.org/showthread.php?t=2322677
[2]: https://bugs.launchpad.net/ubuntu/+source/procps/+bug/1577297

Use pkill instead of xargs + kill

---

lib/chromedriver.js
package.json
test/chromedriver-specs.js

Appium start a webview session by establishing a connection between ADB with chromedriver. It kill all of chromedriver processes existed. After establishing a connection ADB will listen on a random tcp port and chromedriver will connect this port. This port was been listening after chromedriver process has been killed. The quantity of ports listened by adb will increased one by one until exhausted if switch context to webview frequently.
So I add some code into appium-chromedriver/lib/chromedriver.js file

Clean adb forward resource when kill chromedriver process

---

lib/chromedriver.js

If getting the forwarded ports fails, log the error and move on.

Add error handling to port forward check

---

lib/chromedriver.js
lib/install.js

Chromedriver version 2.33 is out, which allows webviews to be automated on Android 8

Update CD version to 2.33

---

lib/install.js
test/install-specs.js

Details of ChromeDriver 2.34 ([full details](https://chromedriver.storage.googleapis.com/2.34/notes.txt)):
```
Supports Chrome v61-63
Changes include:
* Supports new navigation model in Chrome v63+.
* Fixes a bug where touch in mobile emulation doesn't work.
* Fixes a bug in emulating Android devices.
* Removed Timeline as a supported perf log domain type (no longer supported in Chrome).
```

Update CD to 2.34

---

lib/install.js

[Chromedriver CHANGELOG](https://chromedriver.storage.googleapis.com/2.35/notes.txt).
Supports Chrome v62-64
Changes include:
* Supports persistent connections between client application and ChromeDriver.
* Adds more devices types for mobile emulation.
* Fixes a bug in get local storage command.
* Fixes a compatibility bug that causes JavaScript code execution to fail on some versions of Chrome.
* Uses absolute time in log file.

Upgrade CD to 2.35

---

lib/chromedriver.js
test/chromedriver-specs.js

Currently, the Chromedriver version is stored as a float. This mishandles versions ending in "0", though. For example, version "2.30" becomes "2.3" when cast to a float.
To resolve the issue, version is stored as a string. A unit test is also added to prevent regressions.
Co-authored-by: Umut Umzugur <@umutuzgur>

Fix Chromedriver version parsing bug

---

lib/chromedriver.js
lib/install.js

```
----------ChromeDriver v2.38 (2018-04-17)----------
Supports Chrome v65-67
Resolved issue 2354: The chromedriver crashes/lose connection when navigate to gmail [[Pri-0]]
Resolved issue 2381: Unknown session ID and cannot determine loading status [[Pri-1]]
Resolved issue 2198: ChromeDriver 2.34 doesn't wait until iframe content loads after switching into iframe [[Pri-2]]
Resolved issue 2142: unknown error: Element is not clickable at point - after updating chrome browser and chrome driver to latest version [[Pri-2]]
```

Update CD to 2.38

---

lib/chromedriver.js

If no bundle id is sent in, try to find the correct chrome-webview package version, so this will work for webviews as well as actual Chrome.
This is a breaking change.

Update handling of chrome version

---

lib/chromedriver.js
lib/install.js

```
Supports Chrome v66-68
Resolved issue 2436: ChromeDriver for Android does not provide useful error message for old adb version [[Pri-1]]
Resolved issue 2431: ChromeDriver tests that close Windows are flaky [[Pri-1]]
Resolved issue 2259: Click on component into an Iframe (with container padding > 0) is not working [[Pri-1]]
Resolved issue 2161: ChromeDriver remote debug port reservation race conditions [[Pri-2]]
Resolved issue 2420: Get Alert Text is not returning spec compliant error codes [[Pri-2]]
Resolved issue 2369: Clean up state of androidUseRunningApp feature [[Pri-2]]
Resolved issue 2406: Minimize/Maximize window need a w3c compliant endpoints [[Pri-]]
```

Add CD 2.39

---

lib/chromedriver.js
lib/install.js
lib/utils.js
test/chromedriver-specs.js

```
----------ChromeDriver v2.40 (2018-06-07)----------
Supports Chrome v66-68
Resolved issue 2446: Regression: Chromedriver 2.39 hangs on open when user-data-dir is specified and exists [[Pri-1]]
Resolved issue  779: Make ChromeDriver able to listen on requests from IPv6. [[Pri-1]]
Resolved issue 2339: Chromedriver couldn't find the Android file using valid file path [[Pri-2]]
Resolved issue 2307: /session/:sessionId/send_command and /session/:sessionId/send_command_and_get_result should be changed to be proper extension commands [[Pri-]]
```

Bump CD to 2.40

---

lib/chromedriver.js
lib/install.js
lib/utils.js
test/chromedriver-e2e-specs.js
test/chromedriver-specs.js

Android 7+ use Chrome for backing webviews, not the system webview.
Add an argument to circumvent all discovery and use the CD version installed by the package.

Webview bundleid

---

README.md
lib/chromedriver.js

```
----------ChromeDriver v2.41 (2018-07-27)----------
Supports Chrome v67-69
Resolved issue 2458: Chromedriver fails to start with whitelisted-ips option [[Pri-1]]
Resolved issue 2379: Returned capabilities should include remote debugging port [[Pri-2]]
Resolved issue 1005: driver.manage().window().getSize() is not implemented on Android [[Pri-2]]
Resolved issue 2474: desktop launcher error messages are not readable by users [[Pri-]]
Resolved issue 2496: Fail fast when not able to start binary [[Pri-]]
Resolved issue 1990: Close Window return value does not conform with spec [[Pri-]]
```
https://chromedriver.storage.googleapis.com/index.html?path=2.41/

Update to v2.41

---

lib/install.js
package.json

Remove some unused dependencies, and shift to using `fancy-log`, so the install logs blend into the npm logs.

Clean up install script logging

---

README.md
lib/chromedriver.js

Chromedriver 2.42 has [been released](https://chromedriver.storage.googleapis.com/index.html?path=2.42/):
```txt
----------ChromeDriver v2.42 (2018-09-13)----------
Supports Chrome v68-70
Resolved issue 2144: Test testClickElement from MobileEmulationCapabilityTest class fails on Chromium for all platforms [[Pri-1]]
Resolved issue 2566: whitelisted-ips not working with ipv4 [[Pri-1]]
Resolved issue 2541: chromedriver v2.41 fails to start with whitelisted-ips flag on macOS [[Pri-1]]
Resolved issue 2057: Set Timeouts is not implemented [[Pri-1]]
Resolved issue 1938: Take element screenshot not implemented in Chromedriver [[Pri-2]]
Resolved issue 2550: chromedriver ignores PATH when searching for chrome binary [[Pri-2]]
Resolved issue 1993: Fullscreen Window command not spec compliant …
```

Update to CD 2.42

---

lib/chromedriver.js

```
Supports Chrome v69-71
Changes include:
Fixed Parsing of proxy configuration is not standard compliant
Fixed Launch app command is flaky
Fixed Screenshot of element inside iFrame is taken incorrectly
Added ChromeDriver supports window resizing over a remote connection
Fixed Error codes are not handled in Clear element
Fixed Not waiting until element is visible
Fixed Get element property is not implemented
Fixed Switch to Frame is not spec compliant
Fixed Execute Async Script does not return spec compliant error codes
Fixed Execute Script does not return spec compliant error codes
Fixed Error code in ExecuteGet is not conformant with spec
Fixed Send Alert Text is not returning spec compliant error codes
Fixed clear() on an input type="date" pretends element is not user-editable
Fixed …
```

Upgrade to 2.43

---

lib/chromedriver.js

Currently, we can see below error message when establishing Chromedriver connection fails.
```
[debug] [Chromedriver][Chromedriver] Unable to automate Chrome version because it is too old for this version of Chromedriver.
Changed state to 'stopped'
[Chromedriver] Chrome version on device: Chrome/61.0.3163.98
[Chromedriver] Please see 'https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md'
[Chromedriver] Error: Failed to start Chromedriver session: A new session could not be created. Details: session not created: Chrome version must be >= 69.0.3497.0
[Chromedriver]   (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.0 x86_64)
[Chromedriver]     at Object.wrappedLogger.errorAndThrow …
```

return chrome version on device to clients when startSession fails

---

lib/chromedriver.js

Chromium has an unsupported command line option `--disable-build-check` (https://chromium.googlesource.com/chromium/src.git/+/master/chrome/test/chromedriver/chrome_launcher.cc#248) which gets rid of the check for Chrome version on the device. Since the check is a massive pain, give the option to turn that flag on.

Add disableBuildCheck opt

---

lib/chromedriver.js

Chromedriver 2.44 [was released](https://chromedriver.storage.googleapis.com/2.44/notes.txt):
```
----------ChromeDriver v2.44 (2018-11-19)----------
Supports Chrome v69-71
Resolved issue 2522: Test ChromeDriverTest.testWindowMaximize is failing on Mac build bot on Waterfall [[Pri-2]]
Resolved issue 2615: Incorrect 'alert open error' for window handle call [[Pri-2]]
Resolved issue 2649: Element Send Keys should get "text" property in W3C mode [[Pri-2]]
Resolved issue 1995: XML special case of Is Element Enabled is not handled as per spec [[Pri-2]]
Resolved issue 1994: XML special case of Get Element CSS Value is not handled as per spec [[Pri-2]]
Resolved issue 2655: Set Window Rect needs to check for invalid input [[Pri-3]]
Resolved issue 2597: Support new unhandledPromptBehavior modes …
```

Update to CD 2.44

---

lib/chromedriver.js

The current solution is based on loops and difficult to read syntax.
Moreover, sometimes used command hangs up for some time and makes execution really slow. 
To improve and simplify that process on Windows machines, new command based on `wmic` for killing `chromedriver` is proposed.

Improved a way of killing driver on Windows

---

README.md
lib/chromedriver.js

Chromedriver 2.46 has been released:
```
----------ChromeDriver v2.46 (2019-02-01)----------
Supports Chrome v71-73
Resolved issue 2728: Is Element Displayed command does not work correctly with v0 shadow DOM inserts [[Pri-1]]
Resolved issue  755: /session/:sessionId/doubleclick only generates one set of mousedown/mouseup/click events [[Pri-2]]
Resolved issue 2744: Execute Script returns wrong error code when JavaScript returns a cyclic data structure [[Pri-2]]
Resolved issue 1529: OnResponse behavior can lead to port exhaustion [[Pri-2]]
Resolved issue 2736: Close Window command should handle user prompts based on session capabilities [[Pri-2]]
Resolved issue 1963: Sending keys to disabled element should throw Element Not interactable error [[Pri-2]]
Resolved issue 2679: Timeout value …
```

Add Chromedriver 2.46

---

.travis.yml
README.md
install-npm.js
package.json

It is sometimes advantageous to be able to install Appium without installing the Chromedriver 
binary. This PR adds the option to do so, either with
```
APPIUM_SKIP_CHROMEDRIVER_INSTALL=1 npm install -g appium
```
or 
```
npm install -g appium --chromedriver-skip-install
```

Add flag to skip binary download/install

---

lib/chromedriver.js

[Notes](https://chromedriver.storage.googleapis.com/74.0.3729.6/notes.txt):
```
----------ChromeDriver v74.0.3729.6 (2019-03-14)----------
Supports Chrome v74
Resolved issue 2799: Recent change to WebDriver Tests causes ChromeDriver to fail W3C Tests [[Pri-]]
Resolved issue 2798: GET /sessions is not working if at least one of the sessions is in W3C mode [[Pri-3]]
Resolved issue 2783: Improper UTF-8 encoding for CSS child selectors (driver.page_source) [[Pri-]]
Resolved issue 2782: ChromeDriver can't connect to Chrome when /dev/shm is not available on Linux [[Pri-2]]
Resolved issue 2773: Raise a standard exception when element is overlay by another element [[Pri-2]]
Resolved issue 2768: 2.46 produces unexpected debug.log file if verbose logging is enabled [[Pri-1]]
Resolved issue 2749: …
```

 Add version 74.0.3729.6

---

.gitignore
lib/chromedriver.js
test/chromedriver-specs.js

* Add the explicit version when Chromedriver changed the versioning structure
* Modify the test to also parse the new versions

Do an explicit version check instead of a null check

---

index.js
lib/chromedriver.js
lib/storage-client.js
package.json
test/storage-client-e2e-specs.js
test/storage-client-specs.js

This is the POC implementation of Chromedriver storage client. The client is able to retrieve all chromedrivers from the storage, which match to the server OS and architecture. It is also possible to limit the drivers selection by particular chromedriver version or by minimum browser version.
I'm still not quite sure on where to invoke chromedrivers synchronisation, but any feedback on the current implementation or feature requests are welcome

The client implementation for Chromedriver storage

---

.travis.yml
lib/chromedriver.js

Chromedriver [77.0.3865.40](https://chromedriver.storage.googleapis.com/index.html?path=77.0.3865.40/) was released. Notes:
```
---------ChromeDriver 77.0.3865.40 (2019-08-20)---------
Supports Chrome version 77
Resolved issue 1485: Posting to an iframe blocks commands until returned [Pri-2]
Resolved issue 1616: selenium takesHeapSnapshot get error: org.openqa.selenium.WebDriverException: unknown error: heap snapshot not in JSON format [Pri-3]
Resolved issue 1887: Chromedriver should throw InvalidCookieDomain error while adding cookie with incorrect domain [Pri-]
Resolved issue 1902: Support eager page load strategy [Pri-2]
Resolved issue 1917: Detecting a BASIC auth alert [Pri-3]
Resolved issue 2398: executeAsyncScript should promise-call script, and handle rejected promise [Pri-2] …
```

feat: Add CD 77.0.3865.40

---

lib/chromedriver.js

Add the latest stable version. https://chromedriver.storage.googleapis.com/index.html?path=78.0.3904.70/
```
---------ChromeDriver 78.0.3904.70 (2019-10-21)---------
Supports Chrome version 78
Resolved issue 907: PageLoadTimeout ignored when setting Url [Pri-2]
Resolved issue 2212: Implement Permissions Automation
Resolved issue 3044: Unable to interact with dropdown options using Action in ChromeDriver 76 [Pri-2]
Resolved issue 3047: No matching capabilities found if ChromeOptions() is used [Pri-2]
Resolved issue 3074: Adding function to Object.prototype causes difficulties in JavaScript deserialization [Pri-1]
Resolved issue 3078: ChromeDriver 77.0.3865.19 and later does not work with Android [Pri-1]
Resolved issue 3084: Find Elements not working properly in ChromeDriver 76 when …
```

feat: add CD 78.0.3904.70

---

lib/chromedriver.js

Addresses https://github.com/appium/appium/issues/13602

fix: Do not throw an exception if no chrome drivers are present initially

---

lib/chromedriver.js

Starting from Android 10, Chrome is no longer used as a WebView provider (unlike on Android 7,8,9). This PR adds support for Chrome version recognition on Android 10.

feat: add support for android 10 to getChromeVersion

---

lib/chromedriver.js

Adds version recognition support for WebView Browser Tester. I.e. makes ChromeDriver version matching and auto-download work when executing Appium tests with `browserName = 'chromium-webview'` capability.

feat: add support for webview browser tester

---

lib/chromedriver.js

https://chromedriver.storage.googleapis.com/index.html?path=79.0.3945.36/
```
---------ChromeDriver 79.0.3945.36 (2019-11-18)---------
Supports Chrome version 79
Resolved issue 2117: Chromedriver locks when an alert()(js) is raised while taking a screenshot [Pri-2]
Resolved issue 2435: Chrome driver reports platform and platformName as XP on Win10 machine [Pri-2]
Resolved issue 2487: "Element is not clickable" when using headless [Pri-]
Resolved issue 3005: WPT test in element_clear "test_not_editable_inputs[hidden]" does not pass [Pri-3]
Resolved issue 3073: Alerts coming from backend response cause ChromeDriver in W3C mode disconnect from browser - unable to interact with Chrome anymore - java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:38699 [Pri-2]
Resolved …
```

feat: update CD to 79

---

lib/chromedriver.js

This error is currently logged and thrown, then caught and logged, all in this package.
```
[debug] [Chromedriver] Found Chrome bundle 'com.android.chrome' version '69.0.3497'
[Chromedriver] No Chromedriver found that can automate Chrome '69.0.3497'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
[Chromedriver] No Chromedriver found that can automate Chrome '69.0.3497'. You could also try to enable automated chromedrivers download server feature. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
```
So, just throw and rely on the later code to log the error.

refactor: do not print error when no cd found

---

lib/chromedriver.js

Get the latest stable release (https://chromedriver.storage.googleapis.com/index.html?path=80.0.3987.106/)
```
---------ChromeDriver 80.0.3987.106 (2020-02-13)---------
Supports Chrome version 80
Resolved issue 3155: Load page was aborted when using a proxy (v.77/78). [Pri-2]
Resolved issue 3164: Chromedriver version 77 doesn`t wait for page to fully load before interacting with an element [Pri-2]
Resolved issue 3179: ChromeDriver log should include the port used by the driver [Pri-2]
Resolved issue 3180: Enable SetGeoLocation for w3c mode [Pri-]
Resolved issue 3184: UnexpectedAlertOpen status should always include Alert text [Pri-3]
Resolved issue 3188: Improve message when CRX2 Extension is loaded  [Pri-2]
Resolved issue 3196: ChromeDriver 78 race condition in ExecuteGetPageSource may …
```

feat: update to CD 80.0.3987.106

---

.travis.yml

This will prevent duplicate PRs creation for the same release

chore: Give branch the same name as the release name

---

lib/chromedriver.js
test/chromedriver-specs.js

Fixes https://discuss.appium.io/t/appium-with-enabled-chromedriver-autodownload-download-chrome-driver-each-time-before-create-browser-instance/31484

fix: Avoid a redundant Chromedriver download operation if a matching driver is already present

---

package.json

I want to keep base-driver v6 in 1.18 package, so would like to revert the version once.
After creating a new version, I would like to bump up the version again.

chore: revert base driver 7 once to release a new patch version

---

lib/storage-client.js

Hi folks,
I'm using ```chromedriver_autodownload``` feature and I verify the new chromedriver's version has been downloaded.
But I get this error: 
```
[debug] [ChromedriverStorageClient] Selecting chromedrivers whose minimum supported browser version matches to 86
Thg 11 12 22:16:07 node[2780457]: [debug] [ChromedriverStorageClient] Got 3 items
Thg 11 12 22:16:07  node[2780457]: [debug] [ChromedriverStorageClient] Will select candidate drivers versioned as '86.0.4240.22'
Thg 11 12 22:16:07  node[2780457]: [debug] [ChromedriverStorageClient] Selecting chromedrivers whose platform matches to linux64
Thg 11 12 22:16:07 node[2780457]: [debug] [ChromedriverStorageClient] Got 1 item
Thg 11 12 22:16:07 node[2780457]: [debug] [ChromedriverStorageClient] Got 1 driver to sync: [
Thg 11 12 22:16:07 …
```

chore: Adjust permissions for the driver executable

---

lib/chromedriver.js

When testing chromium-browser (custom-built chrome) on
Android 7-9, the version of chrome will be used instead
of the chromium-browser, because the bundleId of webview
bundle will be replaced with CHROME_BUNDLE_ID.
This patch fixes the bug by adding a check checking whether
the bundleId is a webview bundle id or not.

fix: bug in chromium-browser handling for Android 7-9

---

.github/workflows/node.js.yml
lib/install.js
lib/storage-client.js
lib/utils.js
test/install-e2e-specs.js

Now there are separate chromedriver build for M1 mac architecture. Also, the stuff inside of `install.js` mostly duplicates the content of chromedriver storage, so I've refactored it to avoid the unnecessary duplication.

refactor: Update chromedriver retrieval

---

README.md

Add documentation that informs how to skip installation by using the .npmrc file. Refers to https://github.com/appium/appium/issues/15220.

docs: add .npmrc skip method to readme

---

lib/storage-client.js

Currently the M1 executable is also selected on an Intel-based Mac, because `_mac64` is a part of `_mac64_m1`. This fix changes that

fix: Update platform filter regex

---

README.md

Appium 2.0 will accept only environment variable. Appium 1.x can accept the environment variable as well, so we maybe can keep only environment variable way as this readme

docs: leave only environment variable

---

.releaserc

Maybe this will create `refactor` and `chore` sections in the release note as well.
In the default angular one only print feat, fix and perf.
https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/writer-opts.js
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#type
We should set `conventionalcommits` and manually everything to customize it. This PR is based on the angular one, and I have change the `hidden` status in a few to show non-hidden status ones in the release note.
This PR title has `chore` for testing

chore: customize the changelog

---

lib/storage-client.js
lib/types.ts
lib/utils.js
test/functional/storage-client-e2e-specs.js
test/unit/storage-client-specs.js
test/unit/utils-specs.js

This PR fixes an issue where selectMatchingDrivers() ignores `minBroswerVersion` and attempts to download a lot of unnecessary ChromeDrviers.
[Here is a log](https://github.com/appium/appium-uiautomator2-driver/suites/11504452138/artifacts/594646158). While it can detect the Chrome version, it doesn't filter with the minimum browser version. 
```
...... (At Line 12996)
2023-03-12 08:12:37:097 - [debug] [Chromedriver@558d] [Chromedriver@558d] Browser version in the supplied details: Chrome/66.0.3359.158
2023-03-12 08:12:37:097 - [debug] [Chromedriver@558d] [Chromedriver@558d] Found Chrome bundle 'undefined' version '66.0.3359'
...
... (At Line 16182)
2023-03-12 08:12:41:829 - [debug] [ChromedriverStorageClient] [ChromedriverStorageClient] Selecting chromedrivers whose platform matches to …
```

fix: minBrowserVersion in SyncOption should be a number

---

install-npm.js
lib/utils.js

`node install-npm.js` in the current main branch doesn't work due to tsc error.
e.g. https://github.com/appium/appium-chromedriver/actions/runs/4403909094/jobs/7720201682
After letting it show the error details with `util.inspect(e)`, npm install failed like this:
```
npm install
npm WARN config init.author.name Use `--init-author-name` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@20.1.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.1', npm: '8.11.0' }
npm WARN EBADENGINE }
> appium-chromedriver@5.3.0 postinstall
> node install-npm.js
[23:50:48] The Chromedriver install script cannot be found at '/Users/rerorero/go/src/github.com/rerorero/appium-chromedriver/build/lib/install.js'. …
```

fix: install-npm.js fails to run npm run build due to type error

---

lib/chromedriver.js

To support webdriver BiDi, we need to actually return caps that chromedriver returns, since it contains the webSocketUrl value which we may not be able to predict.

fix: start session should return caps that chromedriver returns

---

lib/chromedriver.js
test/unit/chromedriver-specs.js

When executableDir is given, it would be nice to respect executableDir rather than forcefully use system's one for non-adb env such as desktop.
Current implementation does not respect given `executableDir` for non-adb environment. It means automatic detection/download does not work by `getCompatibleChromedriver`.

fix: respect executableDir even non-adb environment such as desktop

---

package.json

…hangelog-conventionalcommits to 8.0.0

chore: bump semantic-release from 23.1.1 to 24.0.0 and conventional-changelog-conventionalcommits to 8.0.0

---

lib/storage-client/storage-client.js
test/helpers/install.js

In `ChromedriverStorageClient`. The caller can get the latest one via `await client.getLatestKnownGoodVersion();`  The latest version is only via chrome labs today.

feat: add get latest known good version

---

.github/workflows/functional-test.yml
lib/chromedriver.js
lib/protocol-helpers.js
test/functional/chromedriver-e2e-specs.js
test/unit/chromedriver-specs.js

BREAKING CHANGE: The `detectWebDriverProtocol` method of the Chromedriver class has been removed
BREAKING CHANGE: The `desiredProtocol` property of the Chromedriver class has been renamed to `_desiredProtocol`
BREAKING CHANGE: The `driverVersion` property of the Chromedriver has been changed to a getter

feat: Determine chromedriver version from the /status API output

---

package.json
test/functional/chromedriver-e2e-specs.js

BREAKING CHANGE: Required Node.js version has been bumped to ^20.19.0 || ^22.12.0 || >=24.0.0
BREAKING CHANGE: Required npm version has been bumped to >=10

feat: Bump Node.js version
